<?php
/**
 * @file
 * Provides a custom search for TextMate lookups.
 */

/**
 * Implementation of hook_perm().
 */
function textmate_api_perm() {
  return array('administer textmate_api', 'use textmate_api');
}

/**
 * Implementation of hook_menu().
 */
function textmate_api_menu() {
  $items = array();

  $items['textmate_api/search/%/%'] = array(
    'title' => 'Search',
    'page callback' => 'textmate_perform_search',
    'page arguments' => array(2),
    'access arguments' => array('use textmate_api'),
  );
  
  return $items;
}

/**
 * Implementation of hook_api_active_branch_alter().
 *
 * Sets the active branch on textmate_api/%/% paths.
 */
function textmate_api_api_active_branch_alter(&$branch) {
  $branches = api_get_branches();

  switch (menu_get_object('node')->path) {
    case '5':
      $branch = $branches[1];
      break;

    case '6':
      $branch = $branches[2];
      break;

    case '7':
      $branch = $branches[3];
      break;

    case '8':
      $branch = $branches[7];
      break;
  }
}

/**
 * Performs the API search.
 */
function textmate_perform_search($branch_name) {
  $keywords = array_slice(arg(), 3);
  $search = array_merge(array($branch_name), $keywords);

  $query = db_query("SELECT b.branch_name, b.project, ad.* FROM {api_branch} b INNER JOIN {api_documentation} ad ON b.branch_id = ad.branch_id LEFT JOIN {api_overrides} ao ON ao.did = ad.did WHERE b.branch_name = '%s' AND (ao.did IS NULL OR ao.root_did = ao.did) AND ad.title IN (" . db_placeholders($keywords, 'varchar') . ")", $search);

  $items = array();
  while ($item = db_fetch_object($query)) {
    $items[] = $item;
  }

  // Exact match found.
  if (count($items) == 1) {
    $branches = api_get_branches();
    drupal_goto(api_url($items[0]));
  }
  else {
    // Trigger default API search.
    drupal_goto('api/search/' . implode('/', $search));
  }
}
